### PR TITLE
Update and rename en.yaml to ru.yaml

### PR DESCRIPTION
**Pull request by user32767**

### CODE REVIEW

**Review by why-not-try-calmer — CHANGES_REQUESTED** [review]
I think you removed `_data/locales/en.yaml`. Merging would delete it from `master`. Can you put it back and move ru.yaml to `_data/locales/ru`?

**Comment by user32767** [comment]
> I think you removed `_data/locales/en.yaml`. Merging would delete it from `master`. Can you put it back and move ru.yaml to `_data/locales/ru`?

I would, if only I knew how to do it... sorry, I shall try to figure out. GitHub seems a bit complex.

**Comment by why-not-try-calmer** [comment]
> > I think you removed `_data/locales/en.yaml`. Merging would delete it from `master`. Can you put it back and move ru.yaml to `_data/locales/ru`?
> 
> I would, if only I knew how to do it... sorry, I shall try to figure out. GitHub seems a bit complex.

Just copy-paste [this](https://raw.githubusercontent.com/openSUSE/newscom/27c0375e82e5bcda3336cdd3c2bf743cbfa6e7c9/_data/locales/en.yaml) into a fresh new `_data/locales/en.yaml`, then commit again

**Review by why-not-try-calmer — APPROVED** [review]

**Comment by why-not-try-calmer** [comment]
Thank you

**Pull request merged**
